language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
    allow_failures:
      - php: nightly
      - php: hhvm
    include:
      - php: 5.4
        env: DEPENDENCIES='low'

sudo: false

cache:
    directories:
      - $HOME/.composer/cache

install:
  - if [ "$DEPENDENCIES" != "low" ]; then composer install --no-interaction; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest --prefer-stable --no-interaction; fi;

script: ./vendor/bin/phpunit --coverage-text
