language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
    allow_failures:
      - php: nightly
      - php: hhvm
    fast_finish: true
    include:
      - php: 5.4
        env: DEPENDENCIES='low'

sudo: false

cache:
    directories:
      - $HOME/.composer/cache/files
      - $HOME/.drush/cache/download

install:
  - if [ "$DEPENDENCIES" != "low" ]; then composer install --no-interaction; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest --prefer-stable --no-interaction; fi;

script:
  - ./vendor/bin/phpunit
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then ./vendor/bin/behat --format progress --strict; fi;
