language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
    allow_failures:
      - php: nightly
      - php: hhvm

install:
  - composer install --dev --prefer-source --no-interaction

script: ./vendor/bin/phpunit --coverage-text
