language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
    allow_failures:
      - php: nightly
      - php: hhvm

sudo: false

cache:
    directories:
      - $HOME/.composer/cache

install:
  - composer install --dev --no-interaction

script: ./vendor/bin/phpunit --coverage-text
