services:

  elife.isolated_drupal_behat.drupal:
    class: eLife\IsolatedDrupalBehatExtension\Drupal
    public: false
    arguments:
      - %drupal.driver.drupal.drupal_root%
      - %mink.base_url%
      - %elife_drupal_behat.profile%

  elife.isolated_drupal_behat.symfony_filesystem:
    class: Symfony\Component\Filesystem\Filesystem
    public: false
